remote_theme: jmelancon/monotheme

title: "massmusicconvert: mass music conversion for the masses"
project_name: "massmusicconvert"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://massmusicconvert.jmelancon.com" # the base hostname & protocol for your site, e.g. http://example.com
footer_text: "jmelancon/massmusicconvert" # text that goes in the lower left of the screen on the footer. for example, your project's repo name.

# Theming
colors:
    primary: "#1E1E20"
    secondary: "#252527"
    tertiary: "#424247"
    accent: Gainsboro
    text: Gainsboro
    textbox: "#424247"
    links: Gainsboro
mobile:
    header_text_size: 6

plugins:
  - jemoji
